[build]
  command = "node scripts/set-env.js && npm run build"
  publish = "dist/movie-explorer/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
